CREATE TABLE P (ID INT PRIMARY KEY, NAME VARCHAR(8));
INSERT INTO P VALUES (1, 'ANA');
INSERT INTO P VALUES (2, 'IVO');
CREATE INDEX IXNAME ON P (NAME);
BEGIN;
UPDATE P SET NAME='MIRA' WHERE ID=1;
DELETE FROM P WHERE ID=2;
INSERT INTO P VALUES (3, 'ZORA');
SELECT * FROM P ORDER BY ID;
ROLLBACK;
SELECT * FROM P ORDER BY ID;
SELECT * FROM P WHERE NAME='ANA';
SELECT * FROM P WHERE NAME='MIRA';
BEGIN;
UPDATE P SET NAME='MIRA' WHERE ID=1;
COMMIT;
SELECT * FROM P WHERE NAME='MIRA';
BEGIN;
CREATE TABLE TEMP (ID INT);
DROP INDEX IXNAME;
ROLLBACK;
.TABLES
.SCHEMA P
CREATE TABLE C (ID INT PRIMARY KEY, PID INT, FOREIGN KEY (PID) REFERENCES P(ID));
INSERT INTO C VALUES (10, 1);
INSERT INTO C VALUES (11, 99);
DELETE FROM P WHERE ID=1;
UPDATE C SET PID=99 WHERE ID=10;
UPDATE P SET ID=9 WHERE ID=1;
INSERT INTO P VALUES (1, 'DUP');
BEGIN;
DROP TABLE C;
ROLLBACK;
SELECT * FROM C;
DELETE FROM C;
DROP TABLE C;
DELETE FROM P WHERE ID=1;
DROP INDEX IXNAME;
DROP TABLE P;
.TABLES
COMMIT;
ROLLBACK;
.QUIT
